# coding: utf-8

INSTANCES_PROMOTED_NUM = 100
PATTERNS_PROMOTED_NUM = 5
RELATION_BASEDIR = '../data/relation/'
CORPUS_FILENAME = '../corpora/relation//candidate.count'

PATTERN_PRECISION_LOWER_BOUND = 0.5
CANDIDATE_LOWER_BOUND = 2
CANDIDATE_WEIGHT = 1

A_BEFORE_B = 'a'
B_BEFORE_A = 'b'


STATUS_DESC = ['STOP', 'RUNNING']
STATUS_STOP = 0
STATUS_RUNNING = 1